// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;
import ballerina/test;

configurable http:BearerTokenConfig & readonly authConfig = ?;
ConnectionConfig config = {auth : authConfig};
Client baseClient = check new Client(config, serviceUrl = "https://api.hubapi.com/crm/v3/objects/notes");

@test:Config {}
isolated function  testPost-/crm/v3/objects/notes/batch/read_read() {
}

@test:Config {}
isolated function  testPost-/crm/v3/objects/notes/batch/upsert_upsert() {
}

@test:Config {}
isolated function  testPost-/crm/v3/objects/notes/search_doSearch() {
}

@test:Config {}
isolated function  testPost-/crm/v3/objects/notes/batch/update_update() {
}

@test:Config {}
isolated function  testPost-/crm/v3/objects/notes/batch/create_create() {
}

@test:Config {}
isolated function  testPost-/crm/v3/objects/notes/batch/archive_archive() {
}

@test:Config {}
isolated function  testGet-/crm/v3/objects/notes/{noteId}_getById() {
}

@test:Config {}
isolated function  testPatch-/crm/v3/objects/notes/{noteId}_update() {
}

@test:Config {}
isolated function  testDelete-/crm/v3/objects/notes/{noteId}_archive() {
}

@test:Config {}
isolated function  testGet-/crm/v3/objects/notes_getPage() {
}

@test:Config {}
isolated function  testPost-/crm/v3/objects/notes_create() {
}
