[package]
distribution = "2201.10.0"
org = "ballerinax"
name = "hubspot.crm.engagement.notes"
version = "1.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["hubspot", "crm", "engagement", "notes"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-hubspot.crm.engagement.notes"

[build-options]
observabilityIncluded = true

[platform.java17]
graalvmCompatible = true
